### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Bill-Y-Huang** [gothinkster/node-express-realworld-example-app#10]
I found two bugs and made corrections. if I am wrong, please point out:

api/articles.js file:

`// update article
router.put('/:article', auth.required, function(req, res, next) {
  User.findById(req.payload.id).then(function(user){       //added code
    //if(req.article._id.toString() === req.payload.id.toString()){     //original code
    if(req.article.author._id.toString() === req.payload.id.toString()){     //modified code
      if(typeof req.body.article.title !== 'undefined'){
        req.article.title = req.body.article.title;
      }

      if(typeof req.body.article.description !== 'undefined'){
        req.article.description = req.body.article.description;
      }

      if(typeof req.body.article.body !== 'undefined'){
        req.article.body = req.body.article.body;
      }

      req.article.save().then(function(article){
        return res.json({article: article.toJSONFor(user)});
      }).catch(next);
    } else {
      return res.send(403);
    }
  });        //added codes
});

// delete article
router.delete('/:article', auth.required, function(req, res, next) {
  //User.findById(req.payload.id).then(function(){         //original codes
    //if(req.article.author.toString() === req.payload.id.toString()){       //original code
    if(req.article.author._id.toString() === req.payload.id.toString()){      //modified code
      return req.article.remove().then(function(){
        return res.sendStatus(204);
      });
    } else {
      return res.sendStatus(403);
    }
  //});       //original code
});`

**Comment by apai4** [comment]
Good catch, thanks for pointing out these bugs! I'll make a fix for these soon.

You're correct, the update articles endpoint needs to query for the user in order to properly render the JSON, and the user id should be checked against the author id and not the article id.

For the delete request, while it's possible to delete the article without querying the user in the database, I think it's good to do so to make sure the user exists in the database (in case a token for a deleted/banned user is used), but the checks for that are missing. The user query promise should look similar to the favorite/unfavorite requests where we send a 401 response if the user comes back empty, as well as handing any errors to `next`.

**Comment by apai4** [comment]
Fixed with https://github.com/gothinkster/node-express-realworld-example-app/commit/a7bc45508164669dcd072c89818816417dc5c166
